# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.
# 
# 
# Answer: 4613732

a = []
i1, i2 = 1, 1

while i1 <= 4_000_000
  a.push(i1)
  i1, i2 = i2, i1+i2
end

puts a.inject(0) {|sum, num| num % 2 == 0 ? sum+num : sum}